version: "1"

envVarGroups:
 - name: chatchonk-secrets
   envVars:
    - key: SUPABASE_URL
      value: ${chatchonk-secrets.SUPABASE_URL}
    - key: SUPABASE_KEY
      value: ${chatchonk-secrets.SUPABASE_KEY}
    - key: SUPABASE_SERVICE_ROLE_KEY
      value: ${chatchonk-secrets.SUPABASE_SERVICE_ROLE_KEY}
    - key: HUGGINGFACE_API_KEY
      value: ${chatchonk-secrets.HUGGINGFACE_API_KEY}
    - key: CHONK_SECRET_KEY
      value: ${chatchonk-secrets.CHONK_SECRET_KEY}

services:
 - type: web
   name: chatchonk-api
   runtime: docker
   dockerfilePath: Dockerfile          # Moved Dockerfile to project root
   plan: starter
   # ----- Runtime resource limits ---------------------------------
   limits:
     cpu: 1                            # 1 vCPU
     memoryMB: 1024                    # 1 GiB RAM
   # ----------------------------------------------------------------
   disks:
     - name: chatchonk-data
       mountPath: /app/data
       sizeGB: 10
   healthCheckPath: /api/health
   healthCheckTimeoutSeconds: 5        # fail if health endpoint >5 s
   # Startup / readiness probe – delay traffic until healthy
   readinessCheckPath: /api/health
   readinessCheckTimeoutSeconds: 10
   readinessCheckIntervalSeconds: 5

   envVars:
    - key: PORT
      value: "10000"
    - key: PYTHON_VERSION
      value: "3.11"
    - key: ENVIRONMENT
      value: "production"
    - key: DEBUG
      value: "False"
    - key: RELOAD
      value: "False"
    - key: UPLOAD_DIR
      value: "/app/data/uploads"
    - key: TEMP_DIR
      value: "/app/data/tmp"
    - key: EXPORT_DIR
      value: "/app/data/exports"
    - key: TEMPLATES_DIR
      value: "/app/templates"
    - key: ALLOWED_ORIGINS
      value: "https://chatchonkbeta.onrender.com"
    - key: API_V1_STR
      value: "/api"
    - key: PROJECT_NAME
      value: "ChatChonk"
