version: "1"

envVarGroups:
 - name: chatchonk-secrets
   envVars:
    - key: SUPABASE_URL
      value: ${chatchonk-secrets.SUPABASE_URL}
    - key: SUPABASE_KEY
      value: ${chatchonk-secrets.SUPABASE_KEY}
    - key: SUPABASE_SERVICE_ROLE_KEY
      value: ${chatchonk-secrets.SUPABASE_SERVICE_ROLE_KEY}
    - key: HUGGINGFACE_API_KEY
      value: ${chatchonk-secrets.HUGGINGFACE_API_KEY}
    - key: CHONK_SECRET_KEY
      value: ${chatchonk-secrets.CHONK_SECRET_KEY}

services:
 - type: web
   name: chatchonk-api
   runtime: docker
   dockerfilePath: backend/Dockerfile
   plan: starter
   healthCheckPath: /api/health
   envVars:
    - key: PORT
      value: "10000"
    - key: PYTHON_VERSION
      value: "3.11"
    - key: ENVIRONMENT
      value: "production"
    - key: DEBUG
      value: "False"
    - key: RELOAD
      value: "False"
    - key: UPLOAD_DIR
      value: "/app/uploads"
    - key: TEMP_DIR
      value: "/app/tmp"
    - key: EXPORT_DIR
      value: "/app/exports"
    - key: TEMPLATES_DIR
      value: "/app/templates"
    - key: ALLOWED_ORIGINS
      value: "https://your-chatchonk-api-url.onrender.com"
    - key: API_V1_STR
      value: "/api"
    - key: PROJECT_NAME
      value: "ChatChonk"
